Repository depromeet/teum-teum-server, pull requests merged in 2024-02, with the labels that each got.

#174 perf: upgrade GPT-3.5 to GPT-4
  src/main/java/net/teumteum/user/infra/GptInterestQuestion.java
Labels: ⚡️ perf

#175 release: 0.3.4
  src/main/java/net/teumteum/user/infra/GptInterestQuestion.java
Labels: 🔖 release

#176 release :0.3.5
  src/main/java/net/teumteum/teum_teum/service/TeumTeumService.java
Labels: 🔖 release

#177 release 0.3.6
  src/main/java/net/teumteum/teum_teum/service/TeumTeumService.java
Labels: 🔖 release

#182 feat: 모임 종료, 사용자 추천 알림을 추가
  src/main/java/net/teumteum/alert/app/AlertHandler.java
  src/main/java/net/teumteum/alert/app/BeforeMeetingAlertHandler.java
  src/main/java/net/teumteum/alert/controller/AlertController.java
  src/main/java/net/teumteum/alert/domain/Alert.java
  src/main/java/net/teumteum/alert/domain/AlertPublisher.java
  src/main/java/net/teumteum/alert/domain/AlertRepository.java
  src/main/java/net/teumteum/alert/domain/AlertService.java
  src/main/java/net/teumteum/alert/domain/AlertType.java
  src/main/java/net/teumteum/alert/domain/Alertable.java
  src/main/java/net/teumteum/alert/domain/BeforeMeetingAlert.java
  src/main/java/net/teumteum/alert/domain/UserAlertRepository.java
  src/main/java/net/teumteum/alert/domain/UserAlertService.java
  src/main/java/net/teumteum/alert/infra/FcmAlertPublisher.java
  src/main/java/net/teumteum/meeting/domain/BeforeMeetingAlerted.java
  src/main/java/net/teumteum/meeting/domain/EndMeetingAlerted.java
  src/main/java/net/teumteum/meeting/domain/MeetingRepository.java
  src/main/java/net/teumteum/meeting/service/MeetingAlertPublisher.java
  src/main/java/net/teumteum/user/UserRecommended.java
  src/main/resources/db/migration/V11_create_alert.sql
  src/test/java/net/teumteum/alert/domain/UserAlertRepositoryTest.java
  src/test/resources/schema.sql
Labels: ✨ feature

#185 feat: 유저가 한달 동안 받은 알람을 조회하는 기능 개발
  src/main/java/net/teumteum/alert/controller/AlertController.java
  src/main/java/net/teumteum/alert/domain/AlertRepository.java
  src/main/java/net/teumteum/alert/domain/AlertService.java
  src/main/java/net/teumteum/alert/domain/response/AlertsResponse.java
  src/main/resources/db/migration/V11__create_alert.sql
  src/test/java/net/teumteum/meeting/domain/MeetingRepositoryTest.java
Labels: ✨ feature

#184 feat: 북마크 추가, 취소 기능 구현
  src/main/java/net/teumteum/meeting/controller/MeetingController.java
  src/main/java/net/teumteum/meeting/domain/Meeting.java
  src/main/java/net/teumteum/meeting/domain/request/UpdateMeetingRequest.java
  src/main/java/net/teumteum/meeting/domain/response/MeetingResponse.java
  src/main/java/net/teumteum/meeting/service/MeetingService.java
  src/main/resources/db/migration/V12__create_bookmark.sql
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
  src/test/java/net/teumteum/meeting/domain/MeetingFixture.java
  src/test/resources/schema.sql
Labels: ✨ feature

#187 release: 0.3.8
  src/main/resources/db/migration/V13__alter_alert_user_id.sql
  src/test/resources/schema.sql
Labels: 🔖 release

#189 refactor: 알람 조회에 읽은알람인지, 언제 발행되었는지를 추가
  src/main/java/net/teumteum/alert/app/AlertHandler.java
  src/main/java/net/teumteum/alert/domain/Alert.java
  src/main/java/net/teumteum/alert/domain/AlertService.java
  src/main/java/net/teumteum/alert/domain/response/AlertsResponse.java
  src/main/resources/db/migration/V14__add_is_read_column_on_alert.sql
  src/test/resources/schema.sql
Labels: ♻️ refactor

#190 release: 0.3.9
  src/main/java/net/teumteum/alert/app/AlertHandler.java
  src/main/java/net/teumteum/alert/domain/Alert.java
  src/main/java/net/teumteum/alert/domain/AlertService.java
  src/main/java/net/teumteum/alert/domain/response/AlertsResponse.java
  src/main/resources/db/migration/V14__add_is_read_column_on_alert.sql
  src/test/resources/schema.sql
Labels: 🔖 release

#179 feat: 회원탈퇴, 로그아웃 시, 회원 위치 데이터 삭제 로직 추가 및 위치 데이터 유효기간 변경
  src/main/java/net/teumteum/core/security/service/RedisService.java
  src/main/java/net/teumteum/teum_teum/domain/response/UserAroundLocationsResponse.java
  src/main/java/net/teumteum/teum_teum/service/TeumTeumService.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
  src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
Labels: ✨ feature, ♻️ refactor, 🐛 bug-fix

#192 feat: 모임 참여자 정보 조회 기능을 구현
  src/main/java/net/teumteum/alert/app/AlertHandler.java
  src/main/java/net/teumteum/meeting/controller/MeetingController.java
  src/main/java/net/teumteum/meeting/domain/response/MeetingParticipantsResponse.java
  src/main/java/net/teumteum/meeting/service/MeetingService.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
Labels: ✨ feature, ♻️ refactor

#194 refactor: 리뷰 피드백 및 테스트 코드 추가 구현
  src/main/java/net/teumteum/alert/app/AlertHandler.java
  src/main/java/net/teumteum/meeting/controller/MeetingController.java
  src/main/java/net/teumteum/meeting/domain/response/MeetingParticipantsForReviewResponse.java
  src/main/java/net/teumteum/meeting/domain/response/MeetingParticipantsResponse.java
  src/main/java/net/teumteum/meeting/service/MeetingService.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
  src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
  src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
Labels: ✨ feature, ♻️ refactor

#197 release: 0.4.1
  src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
Labels: 🔖 release

#200 refactor: Instant를 모두 LocalDateTime으로 변경
  src/main/java/net/teumteum/alert/domain/AlertRepository.java
  src/main/java/net/teumteum/alert/domain/AlertService.java
  src/main/java/net/teumteum/alert/domain/response/AlertsResponse.java
  src/main/java/net/teumteum/core/entity/TimeBaseEntity.java
Labels: ♻️ refactor

#201 release: 0.4.1
  src/main/java/net/teumteum/alert/domain/AlertRepository.java
  src/main/java/net/teumteum/alert/domain/AlertService.java
  src/main/java/net/teumteum/alert/domain/response/AlertsResponse.java
  src/main/java/net/teumteum/core/entity/TimeBaseEntity.java
Labels: 🔖 release

#202 test: 인증 단위 테스트 구현
  src/main/java/net/teumteum/core/security/filter/JwtAuthenticationFilter.java
  src/test/java/net/teumteum/unit/auth/controller/AuthControllerTest.java
  src/test/java/net/teumteum/unit/auth/service/AuthServiceTest.java
  src/test/java/net/teumteum/unit/common/SecurityValue.java
  src/test/java/net/teumteum/unit/core/security/JwtAuthenticationEntryPointTest.java
  src/test/java/net/teumteum/unit/core/security/JwtAuthenticationFilterTest.java
  src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
  src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
Labels: ✅ test, ♻️ refactor

#204 feat: 로그인한 유저가 북마크한 모임 조회
  src/main/java/net/teumteum/meeting/controller/MeetingController.java
  src/main/java/net/teumteum/meeting/domain/MeetingSpecification.java
  src/main/java/net/teumteum/meeting/service/MeetingService.java
  src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
Labels: ✨ feature

#205 release: 0.4.2
  src/main/java/net/teumteum/alert/app/AlertHandler.java
  src/main/java/net/teumteum/alert/domain/AlertService.java
  src/main/java/net/teumteum/alert/infra/FcmAlertPublisher.java
  src/main/java/net/teumteum/core/security/filter/JwtAuthenticationFilter.java
  src/main/java/net/teumteum/meeting/controller/MeetingController.java
  src/main/java/net/teumteum/meeting/domain/MeetingSpecification.java
  src/main/java/net/teumteum/meeting/service/MeetingAlertPublisher.java
  src/main/java/net/teumteum/meeting/service/MeetingService.java
  src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
  src/test/java/net/teumteum/unit/auth/controller/AuthControllerTest.java
  src/test/java/net/teumteum/unit/auth/service/AuthServiceTest.java
  src/test/java/net/teumteum/unit/common/SecurityValue.java
  src/test/java/net/teumteum/unit/core/security/JwtAuthenticationEntryPointTest.java
  src/test/java/net/teumteum/unit/core/security/JwtAuthenticationFilterTest.java
  src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
  src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
Labels: 🔖 release

#207 fix: 북마크기능에 모든 모임이 조회되도록 변경
  src/main/java/net/teumteum/meeting/controller/MeetingController.java
  src/main/java/net/teumteum/meeting/service/MeetingService.java
Labels: 🐛 bug-fix

#211 release: 0.4.7
  src/main/java/net/teumteum/meeting/service/MeetingService.java
Labels: 🔖 release

#215 fix: 소셜 로그인 에러 긴급 수정
  src/main/java/net/teumteum/alert/app/AlertHandler.java
  src/main/java/net/teumteum/core/security/filter/JwtAuthenticationFilter.java
Labels: 🐛 bug-fix

#216 release: 0.5.0
  src/main/java/net/teumteum/alert/app/AlertHandler.java
  src/main/java/net/teumteum/core/security/filter/JwtAuthenticationFilter.java
Labels: 🔖 release

#218 feat: 기존 회원 리뷰 조회 API 로직 변경
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/domain/UserRepository.java
  src/main/java/net/teumteum/user/domain/response/UserReviewResponse.java
  src/main/java/net/teumteum/user/domain/response/UserReviewsResponse.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
  src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
  src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
  src/test/java/net/teumteum/user/domain/UserRepositoryTest.java
Labels: ✨ feature, ♻️ refactor

#226 feat: 유저가 삭제되었을때, 알람토큰도 삭제하도록 수정
  src/main/java/net/teumteum/alert/app/AlertHandler.java
  src/main/java/net/teumteum/alert/domain/UserAlertService.java
  src/main/java/net/teumteum/user/domain/UserDeletedEvent.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
  src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
Labels: ✨ feature

#227 release: 0.5.5
  src/main/java/net/teumteum/alert/app/AlertHandler.java
  src/main/java/net/teumteum/alert/domain/UserAlertService.java
  src/main/java/net/teumteum/user/domain/UserDeletedEvent.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
  src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
Labels: 🔖 release

#231 fix: 모임 시작, 종료 알림이 모임 참여자가 3명 이상이 아니라면, 발행되지않도록 수정
  src/main/java/net/teumteum/meeting/service/MeetingAlertPublisher.java
Labels: 🐛 bug-fix

#229 feat: 리뷰 등록시 모임 참여 유저 조회 API 수정
  src/main/java/net/teumteum/meeting/controller/MeetingController.java
  src/main/java/net/teumteum/meeting/domain/response/MeetingParticipantResponse.java
  src/main/java/net/teumteum/meeting/service/MeetingService.java
  src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
  src/test/java/net/teumteum/integration/Repository.java
  src/test/java/net/teumteum/meeting/domain/MeetingFixture.java
  src/test/java/net/teumteum/unit/meeting/controller/MeetingControllerTest.java
  src/test/java/net/teumteum/unit/meeting/service/MeetingServiceTest.java
  src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
Labels: ✨ feature, ♻️ refactor

#232 release: 0.5.6
  src/main/java/net/teumteum/alert/infra/FcmAlertPublisher.java
  src/main/java/net/teumteum/meeting/controller/MeetingController.java
  src/main/java/net/teumteum/meeting/domain/response/MeetingParticipantResponse.java
  src/main/java/net/teumteum/meeting/service/MeetingAlertPublisher.java
  src/main/java/net/teumteum/meeting/service/MeetingService.java
  src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
  src/test/java/net/teumteum/integration/Repository.java
  src/test/java/net/teumteum/meeting/domain/MeetingFixture.java
  src/test/java/net/teumteum/unit/meeting/controller/MeetingControllerTest.java
  src/test/java/net/teumteum/unit/meeting/service/MeetingServiceTest.java
  src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
Labels: 🔖 release

#233 feat: 리뷰 등록시 요청 DTO Validation 변경 및 로직 추가
  src/main/java/net/teumteum/core/security/SecurityConfig.java
  src/main/java/net/teumteum/user/domain/request/ReviewRegisterRequest.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/test/java/net/teumteum/integration/Repository.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
  src/test/java/net/teumteum/meeting/domain/MeetingFixture.java
  src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
  src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
Labels: ✨ feature, ♻️ refactor

#234 release: 0.5.7
  src/main/java/net/teumteum/core/security/SecurityConfig.java
  src/main/java/net/teumteum/user/domain/request/ReviewRegisterRequest.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/test/java/net/teumteum/integration/Repository.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
  src/test/java/net/teumteum/meeting/domain/MeetingFixture.java
  src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
  src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
Labels: 🔖 release

#220 feat: 위치 기반 API Gatling 부하 테스트
  .gitignore
  Docker-compose.yml
  src/gatling/java/protocol/Protocol.java
  src/gatling/java/simulation/SimulationSample.java
  src/gatling/java/simulation/TeumTeumApiSimulation.java
  src/gatling/java/simulation/UserApiSimulation.java
Labels: ✨ feature, ⚡️ perf
