Repository depromeet/teum-teum-server, pull requests merged in 2024-01, with the labels that each got.

#19 feat: 유저 업데이트 기능 추가
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/domain/User.java
  src/main/java/net/teumteum/user/domain/request/UserUpdateRequest.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/test/java/net/teumteum/user/integration/Api.java
  src/test/java/net/teumteum/user/integration/RequestFixture.java
  src/test/java/net/teumteum/user/integration/UserIntegrationTest.java
Labels: ✨ feature

#24 feat: 모임 목록 조회 방식을 수정하고, 다양한 조건에 따라 모임 검색이 가능하는 기능 구현
  src/main/java/net/teumteum/meeting/controller/MeetingController.java
  src/main/java/net/teumteum/meeting/domain/MeetingRepository.java
  src/main/java/net/teumteum/meeting/domain/MeetingSpecification.java
  src/main/java/net/teumteum/meeting/domain/ResultCursor.java
  src/main/java/net/teumteum/meeting/domain/response/MeetingsResponse.java
  src/main/java/net/teumteum/meeting/model/PageDto.java
  src/main/java/net/teumteum/meeting/service/MeetingService.java
  src/test/java/net/teumteum/meeting/config/PageableHandlerMethodArgumentResolver.java
  src/test/java/net/teumteum/meeting/domain/MeetingFixture.java
  src/test/java/net/teumteum/meeting/domain/MeetingRepositoryTest.java
  src/test/java/net/teumteum/meeting/integration/Api.java
  src/test/java/net/teumteum/meeting/integration/MeetingIntegrationTest.java
  src/test/java/net/teumteum/meeting/integration/Repository.java
Labels: ✨ feature

#25 feat: 친구 맺기 API 개발
  src/main/java/net/teumteum/core/context/LoginContext.java
  src/main/java/net/teumteum/core/context/LoginContextImpl.java
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/domain/User.java
  src/main/java/net/teumteum/user/domain/request/UserUpdateRequest.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V3__add_friends_to_users.sql
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/IntegrationTest.java
  src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
  src/test/java/net/teumteum/integration/Repository.java
  src/test/java/net/teumteum/integration/RequestFixture.java
  src/test/java/net/teumteum/integration/TestLoginContext.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
  src/test/java/net/teumteum/meeting/integration/Api.java
  src/test/java/net/teumteum/meeting/integration/IntegrationTest.java
  src/test/java/net/teumteum/user/domain/UserFixture.java
  src/test/java/net/teumteum/user/integration/Api.java
  src/test/java/net/teumteum/user/integration/Repository.java
  src/test/resources/application.properties
  src/test/resources/schema.sql
Labels: ✨ feature

#27 feat: 유저의 친구 조회 API
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/domain/response/FriendsResponse.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
Labels: ✨ feature

#30 feat: application.yml profile 별 분리 및 인증 로직 기본 구현, JWT 관련 로직 구현
  gradle/spring.gradle
  src/main/java/net/teumteum/Application.java
  src/main/java/net/teumteum/core/config/AppConfig.java
  src/main/java/net/teumteum/core/context/LoginContext.java
  src/main/java/net/teumteum/core/context/LoginContextImpl.java
  src/main/java/net/teumteum/core/entity/TimeBaseEntity.java
  src/main/java/net/teumteum/core/property/JwtProperty.java
  src/main/java/net/teumteum/core/property/RedisProperty.java
  src/main/java/net/teumteum/core/security/Authenticated.java
  src/main/java/net/teumteum/core/security/SecurityConfig.java
  src/main/java/net/teumteum/core/security/UserAuthentication.java
  src/main/java/net/teumteum/core/security/dto/TokenResponse.java
  src/main/java/net/teumteum/core/security/filter/JwtAuthenticationFilter.java
  src/main/java/net/teumteum/core/security/service/AuthService.java
  src/main/java/net/teumteum/core/security/service/JwtService.java
  src/main/java/net/teumteum/core/security/service/RedisService.java
  src/main/java/net/teumteum/core/security/service/SecurityService.java
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/domain/OAuth.java
  src/main/java/net/teumteum/user/domain/Oauth.java
  src/main/java/net/teumteum/user/domain/RoleType.java
  src/main/java/net/teumteum/user/domain/User.java
  src/main/java/net/teumteum/user/domain/UserConnector.java
  src/main/java/net/teumteum/user/domain/request/UserUpdateRequest.java
  src/main/java/net/teumteum/user/domain/response/UserGetResponse.java
  src/main/java/net/teumteum/user/domain/response/UsersGetByIdResponse.java
  src/main/java/net/teumteum/user/service/UserConnectorImpl.java
  src/main/resources/application-auth.yml
  src/main/resources/application-datasource.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-redis.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__create_users.sql
  src/main/resources/db/migration/V4__update_users.sql
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/IntegrationTest.java
  src/test/java/net/teumteum/integration/Repository.java
  src/test/java/net/teumteum/integration/SecurityContextSetting.java
  src/test/java/net/teumteum/integration/TestLoginContext.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
  src/test/java/net/teumteum/user/domain/UserFixture.java
  src/test/java/net/teumteum/user/domain/UserRepositoryTest.java
  src/test/java/net/teumteum/user/service/UserConnectorTest.java
  src/test/resources/application.properties
  src/test/resources/schema.sql
Labels: ✨ feature

#34 feat: 유저 모임 참여 기능 구현
  src/main/java/net/teumteum/meeting/controller/MeetingController.java
  src/main/java/net/teumteum/meeting/domain/Meeting.java
  src/main/java/net/teumteum/meeting/domain/response/MeetingResponse.java
  src/main/java/net/teumteum/meeting/domain/response/MeetingsResponse.java
  src/main/java/net/teumteum/meeting/service/MeetingService.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
  src/test/java/net/teumteum/integration/Repository.java
  src/test/java/net/teumteum/meeting/domain/MeetingFixture.java
Labels: ✨ feature

#35 feat: 유저가 참여한 모임을 취소한다.
  src/main/java/net/teumteum/meeting/controller/MeetingController.java
  src/main/java/net/teumteum/meeting/domain/Meeting.java
  src/main/java/net/teumteum/meeting/service/MeetingService.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
Labels: ✨ feature

#37 feat: 공통 관심질문 생성 기능 개발
  gradle.properties
  gradle/test.gradle
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/domain/InterestQuestion.java
  src/main/java/net/teumteum/user/domain/response/InterestQuestionResponse.java
  src/main/java/net/teumteum/user/infra/GptInterestQuestion.java
  src/main/java/net/teumteum/user/infra/WebClientConfigurer.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/main/resources/application-prod.yml
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/IntegrationTest.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
  src/test/java/net/teumteum/user/infra/GptInterestQuestionTest.java
  src/test/java/net/teumteum/user/infra/GptTestServer.java
  src/test/resources/application.properties
Labels: ✨ feature

#38 feat: Sentry 연동
  build.gradle
  gradle.properties
  gradle/apm.gradle
  settings.gradle
  src/main/java/net/teumteum/core/advice/GlobalExceptionHandler.java
  src/main/java/net/teumteum/meeting/controller/MeetingController.java
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/resources/application-prod.yml
Labels: ✨ feature

#39 feat: 인증 로직 리팩토링 및 추가 구현, 카카오,네이버 소셜 로그인 관련 설정 추가
  gradle/devtool.gradle
  gradle/spring.gradle
  src/main/java/net/teumteum/core/security/Authenticated.java
  src/main/java/net/teumteum/core/security/SecurityConfig.java
  src/main/java/net/teumteum/core/security/UserAuthentication.java
  src/main/java/net/teumteum/core/security/filter/JwtAuthenticationFilter.java
  src/main/resources/application-auth.yml
  src/main/resources/application-datasource.yml
  src/main/resources/application-dev.yml
  src/main/resources/db/migration/V4__update_users.sql
Labels: ✨ feature

#46 refactor: 소셜 로그인 관련 에러 수정 및 exception handler 추가
  src/main/java/net/teumteum/auth/controller/OAuthLoginController.java
  src/main/java/net/teumteum/auth/domain/CustomOAuthUser.java
  src/main/java/net/teumteum/auth/domain/KakaoOAuthUserInfo.java
  src/main/java/net/teumteum/auth/domain/NaverOAuthUserInfo.java
  src/main/java/net/teumteum/auth/domain/OAuthToken.java
  src/main/java/net/teumteum/auth/domain/OAuthUserAttributes.java
  src/main/java/net/teumteum/auth/domain/OAuthUserInfo.java
  src/main/java/net/teumteum/auth/domain/response/TokenResponse.java
  src/main/java/net/teumteum/auth/service/AuthService.java
  src/main/java/net/teumteum/auth/service/OAuthService.java
  src/main/java/net/teumteum/core/security/SecurityConfig.java
  src/main/java/net/teumteum/core/security/config/CorsConfig.java
  src/main/java/net/teumteum/core/security/filter/JwtAccessDeniedHandler.java
  src/main/java/net/teumteum/core/security/filter/JwtAuthenticationEntryPoint.java
  src/main/java/net/teumteum/core/security/filter/JwtAuthenticationFilter.java
  src/main/java/net/teumteum/core/security/service/JwtService.java
  src/main/java/net/teumteum/core/security/service/RedisService.java
  src/main/java/net/teumteum/core/security/service/SecurityService.java
  src/main/java/net/teumteum/user/infra/WebClientConfigurer.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/resources/application.properties
Labels: ♻️ refactor

#45 refactor: 공통 관심 주제 게임 응답으로 관심 질문을 받아볼 수 있도록 추가
  build.gradle
  gradle/sentry.gradle
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/domain/BalanceGameType.java
  src/main/java/net/teumteum/user/domain/InterestQuestion.java
  src/main/java/net/teumteum/user/domain/response/BalanceQuestionResponse.java
  src/main/java/net/teumteum/user/domain/response/InterestQuestionResponse.java
  src/main/java/net/teumteum/user/domain/response/StoryQuestionResponse.java
  src/main/java/net/teumteum/user/infra/GptInterestQuestion.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/test/java/net/teumteum/user/infra/GptInterestQuestionTest.java
Labels: ♻️ refactor

#51 feat: Redis 관련 설정 클래스를 구현하고 적용한다.
  src/main/java/net/teumteum/auth/service/OAuthService.java
  src/main/java/net/teumteum/core/config/RedisConfig.java
  src/main/java/net/teumteum/core/security/service/JwtService.java
  src/main/java/net/teumteum/core/security/service/RedisService.java
  src/test/resources/application.properties
Labels: ✨ feature

#50 feat: 회원 탈퇴를 구현한다.
  src/main/java/net/teumteum/auth/domain/response/TokenResponse.java
  src/main/java/net/teumteum/auth/service/OAuthService.java
  src/main/java/net/teumteum/core/config/RedisConfig.java
  src/main/java/net/teumteum/core/security/SecurityConfig.java
  src/main/java/net/teumteum/core/security/service/JwtService.java
  src/main/java/net/teumteum/core/security/service/RedisService.java
  src/main/java/net/teumteum/core/security/service/SecurityService.java
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
  src/test/resources/application.properties
Labels: ✨ feature

#48 feat: AccessToken, RefreshToken 재발급 기능을 구현한다.
  src/main/java/net/teumteum/auth/controller/AuthController.java
  src/main/java/net/teumteum/auth/domain/response/TokenResponse.java
  src/main/java/net/teumteum/auth/service/AuthService.java
  src/main/java/net/teumteum/auth/service/OAuthService.java
  src/main/java/net/teumteum/core/config/RedisConfig.java
  src/main/java/net/teumteum/core/security/SecurityConfig.java
  src/main/java/net/teumteum/core/security/config/CorsConfig.java
  src/main/java/net/teumteum/core/security/filter/JwtAuthenticationFilter.java
  src/main/java/net/teumteum/core/security/service/JwtService.java
  src/main/java/net/teumteum/core/security/service/RedisService.java
  src/main/java/net/teumteum/core/security/service/SecurityService.java
  src/main/java/net/teumteum/meeting/domain/Meeting.java
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/domain/User.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
  src/test/java/net/teumteum/unit/auth/service/AuthServiceTest.java
  src/test/resources/application.properties
Labels: ✨ feature

#54 feat: 모임 생성을 구현한다.
  build.gradle
  gradle.properties
  gradle/aws.gradle
  gradle/spring.gradle
  src/main/java/net/teumteum/meeting/controller/MeetingController.java
  src/main/java/net/teumteum/meeting/domain/ImageUpload.java
  src/main/java/net/teumteum/meeting/domain/Meeting.java
  src/main/java/net/teumteum/meeting/domain/MeetingArea.java
  src/main/java/net/teumteum/meeting/domain/MeetingSpecification.java
  src/main/java/net/teumteum/meeting/domain/request/CreateMeetingRequest.java
  src/main/java/net/teumteum/meeting/domain/response/ImageUploadResponse.java
  src/main/java/net/teumteum/meeting/domain/response/MeetingResponse.java
  src/main/java/net/teumteum/meeting/domain/response/MeetingsResponse.java
  src/main/java/net/teumteum/meeting/infra/ImageUploadService.java
  src/main/java/net/teumteum/meeting/service/MeetingService.java
  src/main/resources/application-aws.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V2__create_meeting.sql
  src/test/java/net/teumteum/meeting/domain/MeetingFixture.java
  src/test/java/net/teumteum/meeting/domain/MeetingRepositoryTest.java
  src/test/resources/application.properties
  src/test/resources/schema.sql
Labels: ✨ feature

#53 회원 카드 등록 API 을 구현한다.
  src/main/java/net/teumteum/core/config/RedisConfig.java
  src/main/java/net/teumteum/core/property/RedisProperty.java
  src/main/java/net/teumteum/core/security/SecurityConfig.java
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/domain/request/UserRegisterRequest.java
  src/main/java/net/teumteum/user/domain/request/UserUpdateRequest.java
  src/main/java/net/teumteum/user/domain/response/UserRegisterResponse.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/test/java/net/teumteum/core/property/PropertyTest.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/RequestFixture.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
  src/test/java/net/teumteum/unit/auth/controller/AuthControllerTest.java
  src/test/resources/application.properties
Labels: ✨ feature

#55 ci: cd 구성
  .github/workflows/deployer.yml
  Dockerfile
  build.gradle
  gradle/sentry.gradle
  src/main/resources/application-datasource.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 👷 ci

#59 release: 0.0.2
  Dockerfile
Labels: 🔖 release

#65 release: 0.0.4
  src/main/resources/application-aws.yml
  src/main/resources/application-prod.yml
Labels: 🔖 release

#68 release: 0.0.5
  Dockerfile
Labels: 🔖 release

#70 fix: user 도메인 스키마가 맞지 않는 버그 수정
  src/main/resources/db/migration/V1__create_users.sql
  src/test/resources/schema.sql
Labels: 🐛 bug-fix

#71 release: 0.0.6
  src/main/resources/db/migration/V1__create_users.sql
  src/test/resources/schema.sql
Labels: 🔖 release

#75 release: 0.0.7
  src/main/resources/db/migration/V4__update_users.sql
  src/test/resources/schema.sql
Labels: 🔖 release

#80 feat: 회원 로그아웃을 구현한다.
  gradle/test.gradle
  src/main/java/net/teumteum/core/security/service/SecurityService.java
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/test/java/net/teumteum/core/config/RedisTestContainerConfig.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/IntegrationTest.java
  src/test/java/net/teumteum/integration/Repository.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
Labels: ✨ feature

#82 refactor: 기존 API & 코드 리팩토링 및 누락된 테스트 코드 구현
  src/main/java/net/teumteum/auth/service/OAuthService.java
  src/main/java/net/teumteum/user/controller/UserController.java
  src/test/java/net/teumteum/core/security/SecurityServiceTest.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/IntegrationTest.java
  src/test/java/net/teumteum/integration/Repository.java
Labels: ♻️ refactor

#79 feat: Redis Test Container 구성 및 회원 탈퇴 테스트 진행
  gradle.properties
  gradle/test.gradle
  src/test/java/net/teumteum/integration/Repository.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
Labels: ✨ feature

#85 release: 0.0.8
  gradle.properties
  gradle/devtool.gradle
  gradle/test.gradle
  src/main/java/net/teumteum/auth/controller/OAuthLoginController.java
  src/main/java/net/teumteum/auth/service/OAuthService.java
  src/main/java/net/teumteum/core/error/ErrorResponse.java
  src/main/java/net/teumteum/core/security/SecurityConfig.java
  src/main/java/net/teumteum/core/security/filter/JwtAuthenticationEntryPoint.java
  src/main/java/net/teumteum/core/security/service/SecurityService.java
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/test/java/net/teumteum/core/config/RedisTestContainerConfig.java
  src/test/java/net/teumteum/core/security/SecurityServiceTest.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/IntegrationTest.java
  src/test/java/net/teumteum/integration/Repository.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
Labels: 🔖 release

#78 feat: 내 정보 조회 API 구현
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/domain/response/UserMeGetResponse.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
Labels: ✨ feature

#87 fix: 운영 서버 Jwt 파싱 에러 해결을 한다.
  src/main/java/net/teumteum/core/security/service/JwtService.java
Labels: 🐛 bug-fix

#88 release: 0.0.9
  src/main/java/net/teumteum/core/security/service/JwtService.java
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/domain/response/UserMeGetResponse.java
Labels: 🔖 release

#90 release: 0.1.1
  .github/workflows/deployer.yml
Labels: 🔖 release

#94 release: 0.1.2
  src/main/java/net/teumteum/user/infra/GptInterestQuestion.java
Labels: 🔖 release

#96 fix: GPT 토큰에 띄어쓰기가 들어가는 버그 수정
  src/main/java/net/teumteum/user/infra/GptInterestQuestion.java
Labels: 🐛 bug-fix

#99 fix: GPT 통신과정중 objectmapper 파싱 버그 수정
  src/main/java/net/teumteum/user/infra/ChatCompletionResponse.java
  src/main/java/net/teumteum/user/infra/GptInterestQuestion.java
  src/test/java/net/teumteum/user/infra/GptInterestQuestionTest.java
Labels: 🐛 bug-fix

#102 feat: 모임 삭제 기능 구현
  src/main/java/net/teumteum/meeting/controller/MeetingController.java
  src/main/java/net/teumteum/meeting/domain/Meeting.java
  src/main/java/net/teumteum/meeting/service/MeetingService.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
  src/test/java/net/teumteum/integration/Repository.java
  src/test/java/net/teumteum/meeting/domain/MeetingFixture.java
  src/test/java/net/teumteum/meeting/domain/MeetingRepositoryTest.java
Labels: ✨ feature

#105 refactor: 기획 변경에 따른 회원 카드 등록 API 리팩토링
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/domain/User.java
  src/main/java/net/teumteum/user/domain/request/UserRegisterRequest.java
  src/main/java/net/teumteum/user/domain/request/UserUpdateRequest.java
  src/main/java/net/teumteum/user/domain/response/UserGetResponse.java
  src/main/java/net/teumteum/user/domain/response/UserMeGetResponse.java
  src/main/java/net/teumteum/user/domain/response/UsersGetByIdResponse.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/main/resources/db/migration/V5__update_users.sql
  src/test/java/net/teumteum/integration/RequestFixture.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
  src/test/java/net/teumteum/unit/auth/common/SecurityValue.java
  src/test/java/net/teumteum/unit/auth/controller/AuthControllerTest.java
  src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
  src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
  src/test/java/net/teumteum/user/domain/UserFixture.java
  src/test/resources/schema.sql
Labels: ✨ feature, ♻️ refactor

#103 refactor: JWT 에러 응답 리팩토링 및 인가 인증 예최 처리 코드 수정
  gradle.properties
  gradle/devtool.gradle
  src/main/java/net/teumteum/auth/service/AuthService.java
  src/main/java/net/teumteum/auth/service/OAuthService.java
  src/main/java/net/teumteum/core/security/filter/JwtAccessDeniedHandler.java
  src/main/java/net/teumteum/core/security/filter/JwtAuthenticationEntryPoint.java
  src/main/java/net/teumteum/core/security/filter/JwtAuthenticationFilter.java
  src/main/java/net/teumteum/core/security/service/JwtService.java
  src/test/java/net/teumteum/core/property/PropertyTest.java
  src/test/java/net/teumteum/unit/auth/service/AuthServiceTest.java
  src/test/resources/application.properties
Labels: ✨ feature, ♻️ refactor, 🐛 bug-fix

#110 fix: flyway 오류 수정
  src/main/resources/db/migration/V6__create_users_interests.sql
Labels: 🐛 bug-fix

#114 refactor: 회원 카드 등록시 JWT 정보도 함께 반환하도록 수정
  src/main/java/net/teumteum/user/domain/response/UserRegisterResponse.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
  src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
  src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
  src/test/java/net/teumteum/user/domain/UserFixture.java
  src/test/resources/application.properties
Labels: ♻️ refactor

#112 fix: 소셜 로그인 관련 500 에러 수정 및 OAuth 로직 일부 개선
  src/main/java/net/teumteum/auth/controller/OAuthLoginController.java
  src/main/java/net/teumteum/auth/domain/KakaoOAuthUserInfo.java
  src/main/java/net/teumteum/auth/domain/OAuthToken.java
  src/main/java/net/teumteum/auth/service/OAuthService.java
  src/main/java/net/teumteum/core/security/SecurityConfig.java
  src/main/resources/application-auth.yml
  src/main/resources/application-datasource.yml
  src/main/resources/favicon.ico
Labels: ♻️ refactor, 🐛 bug-fix

#108 feat: 위치 기반 API 구현 및 테스트
  src/main/java/net/teumteum/core/config/RedisConfig.java
  src/main/java/net/teumteum/core/security/service/RedisService.java
  src/main/java/net/teumteum/teum_teum/controller/TeumTeumController.java
  src/main/java/net/teumteum/teum_teum/domain/UserData.java
  src/main/java/net/teumteum/teum_teum/domain/request/UserLocationRequest.java
  src/main/java/net/teumteum/teum_teum/domain/response/UserAroundLocationsResponse.java
  src/main/java/net/teumteum/teum_teum/service/TeumTeumService.java
  src/test/java/net/teumteum/core/property/PropertyTest.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/IntegrationTest.java
  src/test/java/net/teumteum/integration/RedisRepository.java
  src/test/java/net/teumteum/integration/Repository.java
  src/test/java/net/teumteum/integration/TeumTeumIntegrationTest.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
  src/test/java/net/teumteum/teum_teum/UserLocationFixture.java
  src/test/resources/application.properties
Labels: ✨ feature, ♻️ refactor

#116 release: 0.1.5
  gradle.properties
  gradle/devtool.gradle
  src/main/java/net/teumteum/auth/controller/OAuthLoginController.java
  src/main/java/net/teumteum/auth/domain/KakaoOAuthUserInfo.java
  src/main/java/net/teumteum/auth/domain/OAuthToken.java
  src/main/java/net/teumteum/auth/service/AuthService.java
  src/main/java/net/teumteum/auth/service/OAuthService.java
  src/main/java/net/teumteum/core/config/RedisConfig.java
  src/main/java/net/teumteum/core/security/SecurityConfig.java
  src/main/java/net/teumteum/core/security/filter/JwtAccessDeniedHandler.java
  src/main/java/net/teumteum/core/security/filter/JwtAuthenticationEntryPoint.java
  src/main/java/net/teumteum/core/security/filter/JwtAuthenticationFilter.java
  src/main/java/net/teumteum/core/security/service/JwtService.java
  src/main/java/net/teumteum/core/security/service/RedisService.java
  src/main/java/net/teumteum/meeting/controller/MeetingController.java
  src/main/java/net/teumteum/meeting/domain/Meeting.java
  src/main/java/net/teumteum/meeting/service/MeetingService.java
  src/main/java/net/teumteum/teum_teum/controller/TeumTeumController.java
  src/main/java/net/teumteum/teum_teum/domain/UserData.java
  src/main/java/net/teumteum/teum_teum/domain/request/UserLocationRequest.java
  src/main/java/net/teumteum/teum_teum/domain/response/UserAroundLocationsResponse.java
  src/main/java/net/teumteum/teum_teum/service/TeumTeumService.java
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/domain/User.java
  src/main/java/net/teumteum/user/domain/request/UserRegisterRequest.java
  src/main/java/net/teumteum/user/domain/request/UserUpdateRequest.java
  src/main/java/net/teumteum/user/domain/response/UserGetResponse.java
  src/main/java/net/teumteum/user/domain/response/UserMeGetResponse.java
  src/main/java/net/teumteum/user/domain/response/UserRegisterResponse.java
  src/main/java/net/teumteum/user/domain/response/UsersGetByIdResponse.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/main/resources/application-auth.yml
  src/main/resources/application-datasource.yml
  src/main/resources/db/migration/V5__update_users.sql
  src/main/resources/db/migration/V6__create_users_interests.sql
  src/main/resources/favicon.ico
  src/test/java/net/teumteum/core/property/PropertyTest.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/IntegrationTest.java
  src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
  src/test/java/net/teumteum/integration/RedisRepository.java
  src/test/java/net/teumteum/integration/Repository.java
  src/test/java/net/teumteum/integration/RequestFixture.java
  src/test/java/net/teumteum/integration/TeumTeumIntegrationTest.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
  src/test/java/net/teumteum/meeting/domain/MeetingFixture.java
  src/test/java/net/teumteum/meeting/domain/MeetingRepositoryTest.java
  src/test/java/net/teumteum/teum_teum/UserLocationFixture.java
  src/test/java/net/teumteum/unit/auth/common/SecurityValue.java
  src/test/java/net/teumteum/unit/auth/controller/AuthControllerTest.java
  src/test/java/net/teumteum/unit/auth/service/AuthServiceTest.java
  src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
  src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
  src/test/java/net/teumteum/user/domain/UserFixture.java
  src/test/resources/application.properties
  src/test/resources/schema.sql
Labels: 🔖 release

#115 build: Gatling 세팅
  build.gradle
  gradle.properties
  gradle/gatling.gradle
  src/gatling/java/protocol/Protocol.java
  src/gatling/java/simulation/SimulationSample.java
  src/gatling/resources/gatling.conf
  src/gatling/resources/recorder.conf
Labels: 🏗️ build

#119 feat: 내 정보 조회에 Oauth 정보 추가
  src/main/java/net/teumteum/user/domain/response/UserMeGetResponse.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
Labels: ✨ feature

#121 fix: 모임 목록 조회 조건에 활동 지역 조건이 안걸리는 버그 수정
  src/main/java/net/teumteum/meeting/controller/MeetingController.java
  src/main/java/net/teumteum/meeting/service/MeetingService.java
Labels: 🐛 bug-fix

#122 release: 0.1.6
  build.gradle
  gradle.properties
  gradle/gatling.gradle
  src/gatling/java/protocol/Protocol.java
  src/gatling/java/simulation/SimulationSample.java
  src/gatling/resources/gatling.conf
  src/gatling/resources/recorder.conf
  src/main/java/net/teumteum/meeting/controller/MeetingController.java
  src/main/java/net/teumteum/meeting/service/MeetingService.java
  src/main/java/net/teumteum/user/domain/response/UserMeGetResponse.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
Labels: 🔖 release

#127 fix: 모임 규격 변경
  src/main/java/net/teumteum/meeting/domain/MeetingArea.java
  src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
  src/test/java/net/teumteum/meeting/domain/MeetingFixture.java
Labels: 🐛 bug-fix

#130 refactor: 코드 포매팅 적용
  src/main/java/net/teumteum/meeting/domain/MeetingSpecification.java
  src/main/java/net/teumteum/meeting/domain/request/CreateMeetingRequest.java
  src/main/java/net/teumteum/meeting/domain/response/ImageUploadResponse.java
  src/main/java/net/teumteum/meeting/domain/response/MeetingResponse.java
  src/main/java/net/teumteum/meeting/domain/response/MeetingsResponse.java
  src/main/java/net/teumteum/meeting/infra/ImageUploadService.java
  src/test/java/net/teumteum/meeting/config/PageableHandlerMethodArgumentResolver.java
  src/test/java/net/teumteum/meeting/domain/MeetingFixture.java
Labels: ♻️ refactor

#135 refactor: 유저조회, 자신조회, 유저들 조회 api응답에 친구 수 필드 추가
  src/main/java/net/teumteum/user/domain/response/UserGetResponse.java
  src/main/java/net/teumteum/user/domain/response/UserMeGetResponse.java
  src/main/java/net/teumteum/user/domain/response/UsersGetByIdResponse.java
Labels: ♻️ refactor

#136 release: 0.2.0
  src/main/java/net/teumteum/user/domain/response/UserGetResponse.java
  src/main/java/net/teumteum/user/domain/response/UserMeGetResponse.java
  src/main/java/net/teumteum/user/domain/response/UsersGetByIdResponse.java
Labels: 🔖 release

#138 fix: JWT 재발급 오류 해결
  src/main/java/net/teumteum/auth/service/AuthService.java
  src/main/java/net/teumteum/core/security/service/JwtService.java
  src/main/java/net/teumteum/core/security/service/RedisService.java
  src/test/java/net/teumteum/unit/auth/service/AuthServiceTest.java
Labels: ♻️ refactor, 🐛 bug-fix

#139 refactor: 틈틈 위치 기반 로직 수정 및 테스트
  src/main/java/net/teumteum/core/config/RedisConfig.java
  src/main/java/net/teumteum/core/security/service/RedisService.java
  src/main/java/net/teumteum/teum_teum/controller/TeumTeumController.java
  src/main/java/net/teumteum/teum_teum/domain/UserLocation.java
  src/main/java/net/teumteum/teum_teum/domain/request/UserLocationRequest.java
  src/main/java/net/teumteum/teum_teum/domain/response/UserAroundLocationsResponse.java
  src/main/java/net/teumteum/teum_teum/service/TeumTeumService.java
  src/test/java/net/teumteum/integration/RedisRepository.java
  src/test/java/net/teumteum/integration/Repository.java
  src/test/java/net/teumteum/integration/TeumTeumIntegrationTest.java
  src/test/java/net/teumteum/teum_teum/UserLocationFixture.java
Labels: ♻️ refactor, 🐛 bug-fix

#141 release: 0.2.1
  src/main/java/net/teumteum/auth/service/AuthService.java
  src/main/java/net/teumteum/core/config/RedisConfig.java
  src/main/java/net/teumteum/core/security/service/JwtService.java
  src/main/java/net/teumteum/core/security/service/RedisService.java
  src/main/java/net/teumteum/teum_teum/controller/TeumTeumController.java
  src/main/java/net/teumteum/teum_teum/domain/UserLocation.java
  src/main/java/net/teumteum/teum_teum/domain/request/UserLocationRequest.java
  src/main/java/net/teumteum/teum_teum/domain/response/UserAroundLocationsResponse.java
  src/main/java/net/teumteum/teum_teum/service/TeumTeumService.java
  src/test/java/net/teumteum/integration/RedisRepository.java
  src/test/java/net/teumteum/integration/Repository.java
  src/test/java/net/teumteum/integration/TeumTeumIntegrationTest.java
  src/test/java/net/teumteum/teum_teum/UserLocationFixture.java
  src/test/java/net/teumteum/unit/auth/service/AuthServiceTest.java
Labels: 🔖 release

#143 fix: JWT 파싱 관련 에러 수정
  src/main/java/net/teumteum/core/security/service/JwtService.java
Labels: 🐛 bug-fix

#144 release: 0.2.2
  src/main/java/net/teumteum/core/security/service/JwtService.java
Labels: 🔖 release

#146 feat: 회원 리뷰 등록 기능 구현
  src/main/java/net/teumteum/meeting/domain/MeetingConnector.java
  src/main/java/net/teumteum/meeting/domain/MeetingRepository.java
  src/main/java/net/teumteum/meeting/service/MeetingConnectorImpl.java
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/domain/Review.java
  src/main/java/net/teumteum/user/domain/User.java
  src/main/java/net/teumteum/user/domain/request/ReviewRegisterRequest.java
  src/main/java/net/teumteum/user/domain/request/UserRegisterRequest.java
  src/main/java/net/teumteum/user/domain/request/UserUpdateRequest.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/main/resources/db/migration/V9__create_users_reviews.sql
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/Repository.java
  src/test/java/net/teumteum/integration/RequestFixture.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
  src/test/java/net/teumteum/meeting/service/MeetingConnectorTest.java
  src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
  src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
  src/test/java/net/teumteum/user/domain/UserFixture.java
  src/test/resources/schema.sql
Labels: ✨ feature, ♻️ refactor

#149 refactor: 통합 테스트시 인증 객체 관련 로직 수정
  src/main/java/net/teumteum/core/security/service/SecurityService.java
  src/test/java/net/teumteum/integration/IntegrationTest.java
  src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
  src/test/java/net/teumteum/integration/SecurityContextSetting.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
Labels: ♻️ refactor, 🐛 bug-fix

#155 feat: 모임 신고 기능 구현
  src/main/java/net/teumteum/meeting/controller/MeetingController.java
  src/main/java/net/teumteum/meeting/service/MeetingService.java
Labels: ✨ feature

#153 feat: 모임 수정 기능 추가
  src/main/java/net/teumteum/meeting/controller/MeetingController.java
  src/main/java/net/teumteum/meeting/domain/Meeting.java
  src/main/java/net/teumteum/meeting/domain/request/UpdateMeetingRequest.java
  src/main/java/net/teumteum/meeting/service/MeetingService.java
  src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
Labels: ✨ feature

#152 feat: 유저 리뷰 조회 기능
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/domain/UserRepository.java
  src/main/java/net/teumteum/user/domain/response/UserReviewsResponse.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
  src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
  src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
  src/test/java/net/teumteum/user/domain/UserFixture.java
  src/test/java/net/teumteum/user/domain/UserRepositoryTest.java
Labels: ✨ feature

#159 feat: 모임시작 5분전 알림 기능 추가
  build.gradle
  gradle.properties
  gradle/messaging.gradle
  src/main/java/net/teumteum/Application.java
  src/main/java/net/teumteum/alert/app/AlertExecutorConfigurer.java
  src/main/java/net/teumteum/alert/app/BeforeMeetingAlertHandler.java
  src/main/java/net/teumteum/alert/controller/AlertController.java
  src/main/java/net/teumteum/alert/domain/AlertPublisher.java
  src/main/java/net/teumteum/alert/domain/AlertRepository.java
  src/main/java/net/teumteum/alert/domain/AlertService.java
  src/main/java/net/teumteum/alert/domain/Alertable.java
  src/main/java/net/teumteum/alert/domain/BeforeMeetingAlert.java
  src/main/java/net/teumteum/alert/domain/UserAlert.java
  src/main/java/net/teumteum/alert/domain/request/RegisterAlertRequest.java
  src/main/java/net/teumteum/alert/infra/FcmAlertExecutorConfigurer.java
  src/main/java/net/teumteum/alert/infra/FcmAlertPublisher.java
  src/main/java/net/teumteum/meeting/domain/Meeting.java
  src/main/java/net/teumteum/meeting/domain/MeetingAlerted.java
  src/main/java/net/teumteum/meeting/domain/MeetingRepository.java
  src/main/java/net/teumteum/meeting/service/MeetingAlertPublisher.java
  src/main/resources/db/migration/V10__create_alert.sql
  src/main/resources/teum-teum-12611-firebase-adminsdk-cjyx3-ea066f25ef.json
  src/test/java/net/teumteum/meeting/domain/MeetingFixture.java
  src/test/java/net/teumteum/meeting/domain/MeetingRepositoryTest.java
  src/test/resources/schema.sql
Labels: ✨ feature

#158 feat: 리뷰 등록시 회원 매너 온도 반영 기능 추가 및 리뷰 등록 리팩토링
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/domain/Review.java
  src/main/java/net/teumteum/user/domain/User.java
  src/main/java/net/teumteum/user/domain/request/ReviewRegisterRequest.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/Repository.java
  src/test/java/net/teumteum/integration/RequestFixture.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
  src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
  src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
  src/test/java/net/teumteum/user/domain/UserFixture.java
Labels: ✨ feature, ♻️ refactor

#162 refactor: 회원 탈퇴 URI 변경
  src/main/java/net/teumteum/user/controller/UserController.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
Labels: ♻️ refactor

#164 release: 0.2.5
  src/main/java/net/teumteum/user/controller/UserController.java
  src/main/java/net/teumteum/user/domain/Review.java
  src/main/java/net/teumteum/user/domain/User.java
  src/main/java/net/teumteum/user/domain/request/ReviewRegisterRequest.java
  src/main/java/net/teumteum/user/service/UserService.java
  src/test/java/net/teumteum/integration/Api.java
  src/test/java/net/teumteum/integration/Repository.java
  src/test/java/net/teumteum/integration/RequestFixture.java
  src/test/java/net/teumteum/integration/UserIntegrationTest.java
  src/test/java/net/teumteum/meeting/domain/MeetingRepositoryTest.java
  src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
  src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
  src/test/java/net/teumteum/user/domain/UserFixture.java
Labels: 🔖 release

#166 feat: fcm token 업데이트 api 추가
  src/main/java/net/teumteum/alert/controller/AlertController.java
  src/main/java/net/teumteum/alert/domain/AlertRepository.java
  src/main/java/net/teumteum/alert/domain/AlertService.java
  src/main/java/net/teumteum/alert/domain/UserAlert.java
  src/main/java/net/teumteum/alert/domain/request/UpdateAlertTokenRequest.java
  src/main/resources/db/migration/V10__create_alert.sql
  src/test/java/net/teumteum/alert/domain/AlertRepositoryTest.java
  src/test/resources/schema.sql
Labels: ✨ feature

#169 fix: 모임 수정 시 이미지가 추가되는 버그 수정
  src/main/java/net/teumteum/meeting/service/MeetingService.java
Labels: 🐛 bug-fix
